package prova.exceptions;

public class ErroTratamentoException extends RuntimeException {
    public ErroTratamentoException() {
        super("Erro no tratamento");
    }
}
